name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 0.8-Refractor-&-Cleanup
      - GUI-Rework
      
jobs:
  qodana:
    runs-on: ubuntu-latest
    
    steps:
      - name: Qodana Composite
        uses: Red-Studio-Ragnarok/Qodana-Composite@main
        with:
          qodana_token: ${{ secrets.QODANA_TOKEN }}
